config/routes.rb
TeamSteria::Application.routes.draw do
  
  resources :user_activities

  resources :activities

  devise_for :users

  root 'welcome#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :user_activities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_activity.rb
class UserActivity < ActiveRecord::Base
  belongs_to :activity
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  def create
    @activity = Activity.new(activity_params)

    if @activity.save
      redirect_to @activity, notice: 'Activity was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /activities/1
  def update
    if @activity.update(activity_params)
      redirect_to @activity, notice: 'Activity was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /activities/1
  def destroy
    @activity.destroy
    redirect_to activities_url, notice: 'Activity was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def activity_params
      params.require(:activity).permit(:name, :points)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!

end

app/controllers/user_activities_controller.rb
class UserActivitiesController < ApplicationController
  before_action :set_user_activity, only: [:show, :edit, :update, :destroy]

  # GET /user_activities
  def index
    @user_activities = UserActivity.all
  end

  # GET /user_activities/1
  def show
  end

  # GET /user_activities/new
  def new
    @user_activity = UserActivity.new
  end

  # GET /user_activities/1/edit
  def edit
  end

  # POST /user_activities
  def create

    @user_activity = UserActivity.new(user_activity_params)

    if @user_activity.save
      redirect_to @user_activity, notice: 'User activity was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /user_activities/1
  def update
    if @user_activity.update(user_activity_params)
      redirect_to @user_activity, notice: 'User activity was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /user_activities/1
  def destroy
    @user_activity.destroy
    redirect_to user_activities_url, notice: 'User activity was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_activity
      @user_activity = UserActivity.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_activity_params
      params.require(:user_activity).permit(:minutes, :comment, :activity_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_activities_helper.rb
module UserActivitiesHelper
end

app/views/activities/_form.html.haml
= form_for(@activity) do |f|
  - if @activity.errors.any?
    #error_explanation
      %h2
        = pluralize(@activity.errors.count, "error")
        prohibited this activity from being saved:
      %ul
        - @activity.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :points
    %br/
    = f.number_field :points
  .actions
    = f.submit

app/views/activities/edit.html.haml
%h1 Editing activity
= render 'form'
= link_to 'Show', @activity
|
\#{link_to 'Back', activities_path}

app/views/activities/index.html.haml
%h1 Listing activities
%table
  %thead
    %tr
      %th Name
      %th Points
      %th{colspan: "3"}
  %tbody
    - @activities.each do |activity|
      %tr
        %td= activity.name
        %td= activity.points
        %td= link_to 'Show', activity
        - if current_user.try(:admin?)
          %td= link_to 'Edit', edit_activity_path(activity)
          %td= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' }

- if current_user.try(:admin?)
  = link_to 'New Activity', new_activity_path

app/views/activities/new.html.haml
%h1 New activity
= render 'form'
= link_to 'Back', activities_path

app/views/activities/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @activity.name
%p
  %strong Points:
  = @activity.points
= link_to 'Edit', edit_activity_path(@activity)
|
\#{link_to 'Back', activities_path}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title TeamSteria
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %p.notice= notice
    %p.alert= alert
    = yield

app/views/user_activities/_form.html.haml
= simple_form_for(@user_activity) do |f|
  - if @user_activity.errors.any?
    #error_explanation
      %h2
        = pluralize(@user_activity.errors.count, "error")
        prohibited this user_activity from being saved:
      %ul
        - @user_activity.errors.full_messages.each do |message|
          %li= message

  = f.association :activity, :collection => Activity.all.sort{|a,b| a.name <=> b.name}

  .field
    = f.label :minutes  
    = f.text_field :minutes
  
  .field
    = f.label :comment
    = f.text_field :comment
  
  .actions
    = f.submit

app/views/user_activities/edit.html.haml
%h1 Editing user_activity
= render 'form'
= link_to 'Show', @user_activity
|
\#{link_to 'Back', user_activities_path}

app/views/user_activities/index.html.haml
%h1 Listing user_activities
%table
  %thead
    %tr
      %th Activity
      %th Minutes
      %th Comment
      %th{colspan: "3"}
  %tbody
    - @user_activities.each do |user_activity|
      %tr
        %td= user_activity.activity.name
        %td= user_activity.minutes
        %td= user_activity.comment
        %td= link_to 'Show', user_activity
        %td= link_to 'Edit', edit_user_activity_path(user_activity)
        %td= link_to 'Destroy', user_activity, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New User activity', new_user_activity_path

app/views/user_activities/new.html.haml
%h1 New user_activity
= render 'form'
= link_to 'Tilbake', user_activities_path

app/views/user_activities/show.html.haml
%p#notice= notice
%p
  %strong Minutes:
  = @user_activity.minutes
%p
  %strong Activity:
  = @user_activity.activity.name
%p
  %strong Comment:
  = @user_activity.comment
= link_to 'Edit', edit_user_activity_path(@user_activity)
|
\#{link_to 'Back', user_activities_path}

app/views/welcome/index.html.haml
%h3 Velkommen til TeamSteria!
= link_to("Se poeng pr aktivitet", "#{activities_path}")
= link_to("Registrer ny aktivitet", "#{new_user_activity_path}")